### ISSUE TITLE
Include new MIXINs placeholder flex order

### ISSUE THREAD

**Issue by daniellevautier** [daniellevautier/responsiveSassBoilerplate#5]

**Comment by hlb89** [comment]
Additional mixin:
@mixin transitions($transitionIn, $transitionOut) {
  -webkit-transition:$transitionIn, $transitionOut;
     -moz-transition:$transitionIn, $transitionOut;
      -ms-transition:$transitionIn, $transitionOut;
       -o-transition:$transitionIn, $transitionOut;
          transition:$transitionIn, $transitionOut;
}

**Comment by daniellevautier** [comment]
Will be included in next push
